apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | quote }}
  labels:
    {{- include "helm-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.nodePort }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "helm-charts.selectorLabels" . | nindent 4 }}
