# Default values for myapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: arun1801docker/springboot-k8s-deployment
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.0"

service:
  type: NodePort
  port: 8080
  nodePort: 30163

env:
  envname: DB_HOST
  configMap_key_Ref_name: db-conf
  configMap_key: host


