apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
data:
 username: dGVzdHVzZXI=
 password: dGVzdHVzZXJAMTIz

---
 apiVersion: v1
kind: Secret
metadata:
  name: db-root-credentials
data:
 password: YWRtaW4xMjM=