apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-charts.fullname" . }}
  labels:
    {{- include "helm-charts.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "helm-charts.selectorLabels" . | nindent 4 }}
